development:
  access_key_id: 'YOUR_ACCESS_KEY_ID'
  secret_access_key: 'YOUR_SECRET_ACCESS_KEY'
  dynamo_db_endpoint: 'dynamodb.ap-northeast-1.amazonaws.com'

test:
  access_key_id: 'YOUR_ACCESS_KEY_ID'
  secret_access_key: 'YOUR_SECRET_ACCESS_KEY'
  dynamo_db_endpoint: 'dynamodb.ap-northeast-1.amazonaws.com'

production:
  access_key_id: 'YOUR_ACCESS_KEY_ID'
  secret_access_key: 'YOUR_SECRET_ACCESS_KEY'
  dynamo_db_endpoint: 'dynamodb.ap-northeast-1.amazonaws.com'